version : "3"

services:
  update:
    image: update
    env_file: 
      - .env
    volumes:
      - "./update/update:/update"
    command: ./update
    expose:
      - "8080"
    networks:
      mynet:
        ipv4_address: "172.28.1.1"
  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports: 
      - "15432:5432"
    networks:
      mynet:
        ipv4_address: "172.28.1.10"
    
networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: "172.28.1.0/16"